//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ng2_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PT_Projects
    {
        public System.Guid pt_project_id { get; set; }
        public string pt_project_name { get; set; }
        public string pt_project_desc { get; set; }
        public string pt_project_tech { get; set; }
        public string pt_project_owner { get; set; }
    }
}
