//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ng2_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PT_ProjectDetails
    {
        public System.Guid pt_detail_id { get; set; }
        public System.Guid pt_project_id { get; set; }
        public string pt_detail_priority { get; set; }
        public string pt_detail_task { get; set; }
        public string pt_detail_assignee { get; set; }
        public string pt_detail_description { get; set; }
        public string pt_detail_deliverable { get; set; }
        public Nullable<System.DateTime> pt_detail_eststart { get; set; }
        public Nullable<System.DateTime> pt_detail_estend { get; set; }
        public Nullable<System.DateTime> pt_detail_actstart { get; set; }
        public Nullable<System.DateTime> pt_detail_actend { get; set; }
        public string pt_detail_status { get; set; }
        public bool pt_detail_deleted { get; set; }
        public bool pt_detail_show { get; set; }
    
        public virtual PT_Projects PT_Projects { get; set; }
    }
}
