//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ng2_api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PTContext : DbContext
    {
        public PTContext()
            : base("name=PTContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NG2_Cars> NG2_Cars { get; set; }
        public virtual DbSet<PT_Projects> PT_Projects { get; set; }
        public virtual DbSet<PT_ProjectDetails> PT_ProjectDetails { get; set; }
        public virtual DbSet<PT_FollowUpItems> PT_FollowUpItems { get; set; }
    }
}
