//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ng2_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class set_group
    {
        public string grp_id { get; set; }
        public string grp_name { get; set; }
        public string grp_desc { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    }
}
