//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ng2_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTD_BusinessGroupUsers_LT
    {
        public int BusinessGroupUserID { get; set; }
        public int BusinessGroupID { get; set; }
        public string user_id { get; set; }
    
        public virtual set_user set_user { get; set; }
        public virtual VTD_BusinessGroups_RT VTD_BusinessGroups_RT { get; set; }
    }
}
