//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ng2_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTD_TestEvents_TT
    {
        public VTD_TestEvents_TT()
        {
            this.VTD_VulnerabilitiesTestings_LT = new HashSet<VTD_VulnerabilitiesTestings_LT>();
        }
    
        public int TestEventID { get; set; }
        public System.DateTime TestDate { get; set; }
        public short IsActive { get; set; }
    
        public virtual ICollection<VTD_VulnerabilitiesTestings_LT> VTD_VulnerabilitiesTestings_LT { get; set; }
    }
}
