//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ng2_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTD_BusinessGroups_RT
    {
        public VTD_BusinessGroups_RT()
        {
            this.VTD_Applications_TT = new HashSet<VTD_Applications_TT>();
            this.VTD_BusinessGroupUsers_LT = new HashSet<VTD_BusinessGroupUsers_LT>();
        }
    
        public int BusinessGroupID { get; set; }
        public string KeyContact { get; set; }
        public string BusinessGroupName { get; set; }
    
        public virtual ICollection<VTD_Applications_TT> VTD_Applications_TT { get; set; }
        public virtual ICollection<VTD_BusinessGroupUsers_LT> VTD_BusinessGroupUsers_LT { get; set; }
    }
}
