//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ng2_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTD_VulnerabilitiesApplications_LT
    {
        public int VulnerabilityApplicationID { get; set; }
        public int VulnerabilityID { get; set; }
        public int ApplicationID { get; set; }
        public string URL { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
    
        public virtual VTD_Applications_TT VTD_Applications_TT { get; set; }
        public virtual VTD_Vulnerabilities_TT VTD_Vulnerabilities_TT { get; set; }
    }
}
